//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::BillStatusEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bill")]
pub struct Model {
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "admissionId")]
    pub admission_id: i32,
    #[sea_orm(column_name = "patientId")]
    pub patient_id: i32,
    #[sea_orm(column_name = "hospitalId")]
    pub hospital_id: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub amount: Decimal,
    #[sea_orm(
        column_name = "insuranceCoverage",
        column_type = "Decimal(Some((10, 2)))",
        nullable
    )]
    pub insurance_coverage: Option<Decimal>,
    #[sea_orm(
        column_name = "patientResponsibility",
        column_type = "Decimal(Some((10, 2)))"
    )]
    pub patient_responsibility: Decimal,
    #[sea_orm(column_name = "dueDate")]
    pub due_date: Option<Date>,
    #[sea_orm(column_name = "lineItems", column_type = "JsonBinary", nullable)]
    pub line_items: Option<Json>,
    #[sea_orm(column_name = "paymentDate")]
    pub payment_date: Option<DateTime>,
    #[sea_orm(column_name = "paymentMethod")]
    pub payment_method: Option<String>,
    pub status: BillStatusEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
