//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "inventory")]
pub struct Model {
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "hospitalId")]
    pub hospital_id: i32,
    #[sea_orm(column_name = "itemName")]
    pub item_name: String,
    pub quantity: i32,
    #[sea_orm(column_name = "unitPrice")]
    pub unit_price: Option<i32>,
    #[sea_orm(column_name = "reorderPoint")]
    pub reorder_point: Option<i32>,
    #[sea_orm(column_name = "lastReceivedDate")]
    pub last_received_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
