//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::entity::sea_orm_active_enums::{GenderEnum, BloodTypeEnum};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "patient")]
pub struct Model {
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "hospitalId")]
    pub hospital_id: i32,
    #[sea_orm(column_name = "firstName")]
    pub first_name: String,
    #[sea_orm(column_name = "lastName")]
    pub last_name: String,
    #[sea_orm(column_name = "dateOfBirth")]
    pub date_of_birth: Date,
    pub gender: Option<GenderEnum>,
    pub phone: String,
    pub email: Option<String>,
    pub address: String,
    #[sea_orm(column_name = "emergencyContact")]
    pub emergency_contact: Option<String>,
    #[sea_orm(column_name = "bloodType")]
    pub blood_type: Option<BloodTypeEnum>,
    pub allergies: Option<Vec<String>>,
    #[sea_orm(column_name = "medicalHistory", column_type = "Text", nullable)]
    pub medical_history: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Default, Debug, Serialize, Deserialize, Clone)]
pub struct PatientRequestBody {
    pub first_name: String,
    pub last_name: String,
    pub date_of_birth: Date,
    pub gender: Option<GenderEnum>,
    pub phone: String,
    pub email: Option<String>,
    pub address: String,
    pub emergency_contact: Option<String>,
    pub blood_type: Option<BloodTypeEnum>,
    pub allergies: Option<Vec<String>>,
    pub medical_history: Option<String>,
}