//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::PrescriptionOrderStatusEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "prescription_order")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub hospital_id: i32,
    pub supplier_id: i32,
    pub order_date: DateTime,
    #[sea_orm(column_name = "orderItems", column_type = "Text", nullable)]
    pub order_items: Option<String>,
    #[sea_orm(column_name = "totalAmount")]
    pub total_amount: Option<i32>,
    pub status: Option<PrescriptionOrderStatusEnum>,
    #[sea_orm(column_name = "prescriptionOrderIc")]
    pub prescription_order_ic: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
