//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::StaffRoleEnum;
use crate::entity::person;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "staff")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid, // PK and FK to person
    pub hospital_id: i32,
    pub department_id: i32,
    pub specialization: Option<String>,
    pub role: StaffRoleEnum,
    pub staff_ic: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "person::Entity",
        from = "Column::Id",
        to = "person::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Person,
}

impl ActiveModelBehavior for ActiveModel {}
