//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::AppointmentStatusEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "appointment")]
pub struct Model {
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "patientId")]
    pub patient_id: i32,
    #[sea_orm(column_name = "doctorId")]
    pub doctor_id: i32,
    #[sea_orm(column_name = "hospitalId")]
    pub hospital_id: i32,
    #[sea_orm(column_name = "appointmentDate")]
    pub appointment_date: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub cost: Decimal,
    #[sea_orm(column_name = "scheduledBy")]
    pub scheduled_by: Option<String>,
    #[sea_orm(column_name = "appointmentType")]
    pub appointment_type: Option<String>,
    pub status: AppointmentStatusEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
