//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::admission::Entity as Admission;
pub use super::ambulance::Entity as Ambulance;
pub use super::amenities::Entity as Amenities;
pub use super::appointment::Entity as Appointment;
pub use super::bed::Entity as Bed;
pub use super::bill::Entity as Bill;
pub use super::card::Entity as Card;
pub use super::customers::Entity as Customers;
pub use super::dashboard::Entity as Dashboard;
pub use super::department::Entity as Department;
pub use super::emergency::Entity as Emergency;
pub use super::guard::Entity as Guard;
pub use super::hospital::Entity as Hospital;
pub use super::inventory::Entity as Inventory;
pub use super::medical_record::Entity as MedicalRecord;
pub use super::patient::Entity as Patient;
pub use super::patient_doctor::Entity as PatientDoctor;
pub use super::patient_info::Entity as PatientInfo;
pub use super::prescription::Entity as Prescription;
pub use super::prescription_order::Entity as PrescriptionOrder;
pub use super::room::Entity as Room;
pub use super::staff::Entity as Staff;
pub use super::staff_schedule::Entity as StaffSchedule;
pub use super::supplier::Entity as Supplier;
pub use super::treatment::Entity as Treatment;
