//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "prescription")]
pub struct Model {
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "patientId")]
    pub patient_id: i32,
    #[sea_orm(column_name = "doctorId")]
    pub doctor_id: i32,
    #[sea_orm(column_name = "hospitalId")]
    pub hospital_id: i32,
    pub medication: String,
    pub dosage: String,
    pub frequency: String,
    #[sea_orm(column_name = "startDate")]
    pub start_date: Date,
    #[sea_orm(column_name = "endDate")]
    pub end_date: Date,
    #[sea_orm(column_type = "Text", nullable)]
    pub instructions: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub cost: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
