//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "staff_schedule")]
pub struct Model {
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_name = "staffId")]
    pub staff_id: i32,
    #[sea_orm(column_name = "departmentId")]
    pub department_id: i32,
    #[sea_orm(column_name = "hospitalId")]
    pub hospital_id: i32,
    #[sea_orm(column_name = "scheduleDate")]
    pub schedule_date: Date,
    #[sea_orm(column_name = "startTime")]
    pub start_time: Time,
    #[sea_orm(column_name = "endTime")]
    pub end_time: Time,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
