name: Docker Check - Master

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-check-master.yml'

jobs:
  docker-build:
    name: Verify Docker Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: hospital:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Verify Docker image
        run: |
          docker image inspect hospital:test
          echo "✅ Docker image built successfully"

